-- RANK DA EMPRESA
SELECT COMPANY_RANK FROM COMPANY WHERE COMPANY_ID = '${COMPANY_ID}';

UPDATE COMPANY 
SET COMPANY_RANK = (SELECT AVG(COMMENT_RANK) FROM COMMENT WHERE COMPANY_ID = '${COMPANY_ID}')
WHERE COMPANY_ID = '${COMPANY_ID}'
;

SELECT AVG(COMMENT_RANK) FROM COMMENT WHERE COMPANY_ID = '${COMPANY_ID}';

CALL UPD_COMPANY_RANK;

-- RANK DO PRODUTO POR EMPRESA
SELECT PRODUCT_RANK FROM PRODUCT WHERE PRODUCT_ID = '${PRODUCT_ID}';

UPDATE PRODUCT 
SET PRODUCT_RANK = (SELECT AVG(COMMENT_RANK) 
					FROM COMMENT 
					WHERE PRODUCT_ID = '${PRODUCT_ID}' 
					AND COMPANY_ID = '${COMPANY_ID}')
WHERE PRODUCT_ID = '${PRODUCT_ID}'
;

CALL UPD_PRODUCT_RANK;