SELECT * FROM ADDRESS a ;
SELECT * FROM ADMIN_POST;
SELECT * FROM CATEGORY;
SELECT * FROM COMMENT;
SELECT * FROM COMMENT_EXT ce ;
SELECT * FROM COMPANY;
SELECT * FROM POST;
SELECT * FROM POST_EXT pe ;
SELECT * FROM PRODUCT;
SELECT * FROM SEC_RST_CODE;
SELECT * FROM TAG;
SELECT * FROM USER;
SELECT * FROM USER_TYPE;



