SELECT * FROM ADMIN_POST;
SELECT * FROM CATEGORY;
SELECT * FROM COMMENT;
SELECT * FROM COMPANY;
SELECT * FROM POST;
SELECT * FROM PRODUCT;
SELECT * FROM SEC_RST_CODE;
SELECT * FROM TAG;
SELECT * FROM USER;
SELECT * FROM USER_TYPE;

