SELECT * FROM ADDRESS a ;
SELECT * FROM ADMIN_POST;
SELECT * FROM CATEGORY;
SELECT * FROM COMMENT;
SELECT * FROM COMMENT_EXT ce ;
SELECT * FROM COMPANY;
SELECT * FROM POST;
SELECT * FROM POST_EXT pe ;
SELECT * FROM PRODUCT;
SELECT * FROM SEC_RST_CODE;
SELECT * FROM TAG;
SELECT * FROM USER;
SELECT * FROM USER_TYPE;


CALL INSERT_COMPANY ('COMPANY_NOME', 'COMPANY_LOGIN','COMPANY_EMAIL','COMPANY_PASSWORD','COMPANY_IMAGEM'); 

CALL INSERT_USER ('USER_NOME', 'USER_LOGIN','USER_EMAIL','USER_PASSWORD','USER_IMAGEM');
