/* 
###############################
####### COMMENT_DELETE ##########################################################################################################################################################################################
###############################
*/

CREATE TRIGGER COMMENT_DELETE AFTER UPDATE ON PRODUCT FOR EACH ROW BEGIN
	IF NEW.PRODUCT_STATUS = 'I' THEN
	    UPDATE COMMENT c
	    SET c.COMMENT_STATUS = 'I'
	    WHERE PRODUCT_ID = NEW.PRODUCT_ID;
	END IF;
END

DROP TRIGGER COMMENT_DELETE;
/* 
###############################
####### ASSOCIAR_USER_COMPANY ##########################################################################################################################################################################################
###############################
*/

CREATE TRIGGER ASSOCIAR_USER_COMPANY AFTER INSERT ON USER FOR EACH ROW BEGIN
    IF NEW.USER_TYPE_ID = '8986b070-100b-11f0-ab2e-020017000d59' THEN
        INSERT INTO COMPANY (USER_ID, COMPANY_ID, COMPANY_NAME) VALUES (NEW.USER_ID, UUID(),  NEW.USER_NAME);
    END IF;
END

DROP TRIGGER ASSOCIAR_USER_COMPANY;
/* 
###############################
####### CALCULATE_RANKS ##########################################################################################################################################################################################
###############################
*/

CREATE TRIGGER CALCULATE_PRODUCT_RANK AFTER INSERT ON COMMENT 
FOR EACH ROW 
BEGIN
	DECLARE NEW_PRODUCT_ID BINARY(36);
	SET NEW_PRODUCT_ID = NEW.PRODUCT_ID;
	UPDATE PRODUCT p
	SET p.PRODUCT_RANK = (SELECT AVG(COMMENT_RANK) FROM COMMENT WHERE PRODUCT_ID = NEW_PRODUCT_ID)
	WHERE p.PRODUCT_ID = NEW_PRODUCT_ID;
	UPDATE COMPANY c
	INNER JOIN PRODUCT p ON p.COMPANY_ID = c.COMPANY_ID 
	SET c.COMPANY_RANK = (SELECT AVG(COMMENT_RANK) FROM COMMENT WHERE PRODUCT_ID = NEW_PRODUCT_ID)
	WHERE p.PRODUCT_ID = NEW_PRODUCT_ID;
END

CREATE TRIGGER CALCULATE_PRODUCT_RANK_UPD AFTER UPDATE ON COMMENT 
FOR EACH ROW 
BEGIN
	DECLARE NEW_PRODUCT_ID BINARY(36);
	SET NEW_PRODUCT_ID = NEW.PRODUCT_ID;
	UPDATE PRODUCT p
	SET p.PRODUCT_RANK = (SELECT AVG(COMMENT_RANK) FROM COMMENT WHERE PRODUCT_ID = NEW_PRODUCT_ID)
	WHERE p.PRODUCT_ID = NEW_PRODUCT_ID;
	UPDATE COMPANY c
	INNER JOIN PRODUCT p ON p.COMPANY_ID = c.COMPANY_ID 
	SET c.COMPANY_RANK = (SELECT AVG(COMMENT_RANK) FROM COMMENT WHERE PRODUCT_ID = NEW_PRODUCT_ID)
	WHERE p.PRODUCT_ID = NEW_PRODUCT_ID;
END

DROP TRIGGER CALCULATE_PRODUCT_RANK;
DROP TRIGGER CALCULATE_PRODUCT_RANK_UPD;
