select * from CATEGORY;

-- CATEGORIAS COM TYPE 'SERVICO'
INSERT INTO CATEGORY (CATEGORY_NAME, CATEGORY_TYPE) VALUES ('Consultoria Empresarial', 'SERVICO');
INSERT INTO CATEGORY (CATEGORY_NAME, CATEGORY_TYPE) VALUES ('Desenvolvimento de Software', 'SERVICO');
INSERT INTO CATEGORY (CATEGORY_NAME, CATEGORY_TYPE) VALUES ('Atendimento ao Cliente', 'SERVICO');
INSERT INTO CATEGORY (CATEGORY_NAME, CATEGORY_TYPE) VALUES ('Gestão de Projetos', 'SERVICO');
INSERT INTO CATEGORY (CATEGORY_NAME, CATEGORY_TYPE) VALUES ('SERVICOs de Marketing', 'SERVICO');
INSERT INTO CATEGORY (CATEGORY_NAME, CATEGORY_TYPE) VALUES ('Auditoria Financeira', 'SERVICO');
INSERT INTO CATEGORY (CATEGORY_NAME, CATEGORY_TYPE) VALUES ('Treinamentos Profissionais', 'SERVICO');
INSERT INTO CATEGORY (CATEGORY_NAME, CATEGORY_TYPE) VALUES ('Consultoria em TI', 'SERVICO');
INSERT INTO CATEGORY (CATEGORY_NAME, CATEGORY_TYPE) VALUES ('Design Gráfico', 'SERVICO');
INSERT INTO CATEGORY (CATEGORY_NAME, CATEGORY_TYPE) VALUES ('Segurança Cibernética', 'SERVICO');
-- CATEGORIAS COM TYPE 'PRODUTO'
INSERT INTO CATEGORY (CATEGORY_NAME, CATEGORY_TYPE) VALUES ('Eletrônicos', 'PRODUTO');
INSERT INTO CATEGORY (CATEGORY_NAME, CATEGORY_TYPE) VALUES ('Roupas e Acessórios', 'PRODUTO');
INSERT INTO CATEGORY (CATEGORY_NAME, CATEGORY_TYPE) VALUES ('Móveis e Decoração', 'PRODUTO');
INSERT INTO CATEGORY (CATEGORY_NAME, CATEGORY_TYPE) VALUES ('Alimentos e Bebidas', 'PRODUTO');
INSERT INTO CATEGORY (CATEGORY_NAME, CATEGORY_TYPE) VALUES ('Brinquedos', 'PRODUTO');
INSERT INTO CATEGORY (CATEGORY_NAME, CATEGORY_TYPE) VALUES ('Cosméticos', 'PRODUTO');
INSERT INTO CATEGORY (CATEGORY_NAME, CATEGORY_TYPE) VALUES ('Produtos de Informática', 'PRODUTO');
INSERT INTO CATEGORY (CATEGORY_NAME, CATEGORY_TYPE) VALUES ('Ferramentas e Equipamentos', 'PRODUTO');
INSERT INTO CATEGORY (CATEGORY_NAME, CATEGORY_TYPE) VALUES ('Livros e Materiais Educacionais', 'PRODUTO');
INSERT INTO CATEGORY (CATEGORY_NAME, CATEGORY_TYPE) VALUES ('Produtos para Pets', 'PRODUTO');
