select * from CATEGORY;

-- CATEGORIAS COM TYPE 'SERVICO'
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME, CATEGORY_TYPE) VALUES (UUID(), 'Consultoria Empresarial', 'SERVICO');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME, CATEGORY_TYPE) VALUES (UUID(), 'Desenvolvimento de Software', 'SERVICO');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME, CATEGORY_TYPE) VALUES (UUID(), 'Atendimento ao Cliente', 'SERVICO');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME, CATEGORY_TYPE) VALUES (UUID(), 'Gestão de Projetos', 'SERVICO');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME, CATEGORY_TYPE) VALUES (UUID(), 'SERVICOs de Marketing', 'SERVICO');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME, CATEGORY_TYPE) VALUES (UUID(), 'Auditoria Financeira', 'SERVICO');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME, CATEGORY_TYPE) VALUES (UUID(), 'Treinamentos Profissionais', 'SERVICO');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME, CATEGORY_TYPE) VALUES (UUID(), 'Consultoria em TI', 'SERVICO');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME, CATEGORY_TYPE) VALUES (UUID(), 'Design Gráfico', 'SERVICO');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME, CATEGORY_TYPE) VALUES (UUID(), 'Segurança Cibernética', 'SERVICO');
-- CATEGORIAS COM TYPE 'PRODUTO'
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME, CATEGORY_TYPE) VALUES (UUID(), 'Eletrônicos', 'PRODUTO');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME, CATEGORY_TYPE) VALUES (UUID(), 'Roupas e Acessórios', 'PRODUTO');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME, CATEGORY_TYPE) VALUES (UUID(), 'Móveis e Decoração', 'PRODUTO');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME, CATEGORY_TYPE) VALUES (UUID(), 'Alimentos e Bebidas', 'PRODUTO');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME, CATEGORY_TYPE) VALUES (UUID(), 'Brinquedos', 'PRODUTO');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME, CATEGORY_TYPE) VALUES (UUID(), 'Cosméticos', 'PRODUTO');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME, CATEGORY_TYPE) VALUES (UUID(), 'Produtos de Informática', 'PRODUTO');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME, CATEGORY_TYPE) VALUES (UUID(), 'Ferramentas e Equipamentos', 'PRODUTO');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME, CATEGORY_TYPE) VALUES (UUID(), 'Livros e Materiais Educacionais', 'PRODUTO');
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME, CATEGORY_TYPE) VALUES (UUID(), 'Produtos para Pets', 'PRODUTO');
