INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(2, 'x', 'Smartphone com tela de 6.5 polegadas, câmera de 48MP e bateria de longa duração.', 11, 1, 'A', 0.0, NULL, 'produtos/img1.png', '2025-03-21 15:22:36', '2025-03-27 08:53:52');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(3, 'Camiseta TechFit', 'Camiseta confortável e respirável, ideal para atividades físicas e uso diário.', 12, 2, 'A', 0.0, NULL, 'produtos/img2.png', '2025-03-21 15:22:37', '2025-03-27 08:53:52');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(4, 'Sofá Conforto', 'Sofá de três lugares, com estofamento macio e estrutura resistente.', 13, 3, 'A', 0.0, NULL, 'produtos/img3.png', '2025-03-21 15:22:37', '2025-03-27 08:53:52');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(5, 'Café Gourmet Premium', 'Café gourmet de grãos selecionados, com sabor suave e aroma marcante.', 14, 4, 'A', 0.0, NULL, 'produtos/img4.png', '2025-03-21 15:22:37', '2025-03-27 08:53:52');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(6, 'Drone VisionPro', 'Drone com câmera 4K, ideal para capturar imagens aéreas de alta qualidade.', 15, 5, 'A', 0.0, NULL, 'produtos/img4.png', '2025-03-21 15:22:37', '2025-03-27 08:53:53');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(7, 'Relógio Digital XTime', 'Relógio moderno com pulseira de silicone e funcionalidades como contador de passos e monitoramento cardíaco.', 16, 6, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:37', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(8, 'Luminária LED Smart', 'Luminária com controle de intensidade de luz e opção de cores, ideal para ambientes modernos.', 17, 7, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:37', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(9, 'Mochila TechPack', 'Mochila resistente e espaçosa, projetada para carregar laptops e equipamentos eletrônicos com segurança.', 18, 8, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:37', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(10, 'Fones de Ouvido NoiseBlock', 'Fones de ouvido sem fio com cancelamento de ruído ativo e som de alta qualidade.', 19, 9, 'A', 0.0, NULL, 'produtos/img5.png', '2025-03-21 15:22:37', '2025-03-27 08:53:53');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(11, 'Kit Ferramentas Pro', 'Kit com 100 peças para reparos domésticos e profissionais, incluindo chaves, martelos e alicates.', 20, 10, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:37', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(13, 'Tênis RunningMax', 'Tênis de corrida com tecnologia de amortecimento e design aerodinâmico.', 12, 12, 'A', 0.0, NULL, 'produtos/img2.png', '2025-03-21 15:22:38', '2025-03-27 08:53:53');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(14, 'Ferro de Passar Steamer', 'Ferro a vapor portátil, ideal para passar roupas com facilidade e rapidez.', 13, 13, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:38', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(15, 'Bicicleta Aventura', 'Bicicleta resistente para trilhas e passeios ao ar livre, com suspensão e design robusto.', 14, 14, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:38', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(16, 'Câmera DSLR Pro', 'Câmera profissional com lente intercambiável e sensor de alta resolução.', 15, 15, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:38', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(17, 'Aspirador Robot CleanPro', 'Aspirador de pó robô, com mapeamento inteligente e programação de limpeza.', 16, 16, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:38', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(18, 'Máquina de Café Espresso', 'Máquina de café espresso compacta, ideal para preparar cafés de qualidade em casa.', 17, 17, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:38', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(19, 'Mixer ProCook', 'Mixer de alta potência, ideal para triturar e misturar alimentos rapidamente.', 18, 18, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:38', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(20, 'Smartwatch FitTrack', 'Relógio inteligente com monitoramento de atividades físicas e batimentos cardíacos.', 19, 19, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:38', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(21, 'Câmera de Segurança Wi-Fi', 'Câmera de segurança com conexão Wi-Fi e monitoramento remoto através de app.', 20, 20, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:38', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(22, 'Teclado Gamer Xperience', 'Teclado mecânico com iluminação RGB e teclas programáveis, ideal para gamers.', 11, 21, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:38', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(23, 'Cadeira de Escritório Comfort', 'Cadeira ergonômica para escritório com ajuste de altura e apoio lombar.', 12, 22, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:38', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(24, 'Caixa de Som Bluetooth SoundMax', 'Caixa de som Bluetooth com alta qualidade de som e autonomia de bateria de 12 horas.', 13, 23, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:39', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(25, 'Patins Inline Speed', 'Patins de alta performance, projetados para velocidade e estabilidade.', 14, 24, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:39', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(26, 'Notebook UltraBook Pro', 'Notebook ultra-fino, ideal para profissionais e estudantes que precisam de mobilidade e desempenho.', 15, 25, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:39', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(27, 'Cafeteira Expresso Pro', 'Cafeteira expresso compacta com tecnologia de pressão de 15 bares, ideal para preparar cafés com qualidade profissional.', 16, 26, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:39', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(28, 'Luva de Treinamento MaxFit', 'Luva de treino confortável e resistente, com design anatômico para proteção e conforto.', 17, 27, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:39', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(29, 'Saxofone Profissional Gold', 'Saxofone de alta qualidade, ideal para músicos profissionais e iniciantes que desejam aprimorar suas habilidades.', 18, 28, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:39', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(30, 'Ferro de Passar a Vapor Turbo', 'Ferro de passar a vapor com sistema anti-gotejamento e base de cerâmica, ideal para roupas delicadas.', 19, 29, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:39', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(31, 'Grill Elétrico SmartCook', 'Grill elétrico com ajustes de temperatura e superfícies antiaderentes para grelhar carnes e vegetais.', 20, 30, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:39', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(32, 'Escova Alisadora HairMax', 'Escova alisadora de cabelo com tecnologia iônica, que promove brilho e elimina o frizz.', 11, 31, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:39', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(33, 'Carteira de Couro Luxo', 'Carteira masculina de couro legítimo, com compartimentos para cartões e cédulas.', 12, 32, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:39', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(34, 'Fones de Ouvido In-Ear', 'Fones de ouvido com excelente qualidade de som e design compacto para conforto durante o uso.', 13, 33, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:39', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(35, 'Máquina de Cortar Cabelo ProClip', 'Máquina de cortar cabelo profissional com lâminas de aço inoxidável e regulagem de comprimento.', 14, 34, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:39', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(36, 'Console PlayMax', 'Console de videogame de última geração, com gráficos 4K e um catálogo de jogos diversificado.', 15, 35, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:40', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(37, 'Pistola de Cola Quente', 'Pistola de cola quente ideal para artesanato, com alta eficiência e design ergonômico.', 16, 36, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:40', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(38, 'Garmin GPS Smart', 'GPS inteligente com mapa atualizado e funcionalidades de monitoramento de atividades físicas.', 17, 37, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:40', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(39, 'Escova de Dentes Elétrica OralCare', 'Escova de dentes elétrica com tecnologia de escovação inteligente e temporizador para dentes mais saudáveis.', 18, 38, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:40', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(40, 'Alarme de Segurança HomeGuard', 'Alarme de segurança residencial com sensores de movimento e monitoramento via aplicativo.', 19, 39, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:40', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(41, 'Relógio de Pulso Classic', 'Relógio de pulso clássico, com design simples e elegante, ideal para todas as ocasiões.', 20, 40, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:40', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(42, 'Consultoria Empresarial', 'Consultoria especializada em gestão empresarial para otimizar processos e maximizar lucros.', 1, 1, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:40', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(43, 'Desenvolvimento de Software', 'Serviço de desenvolvimento de software personalizado para atender as necessidades da sua empresa.', 2, 2, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:40', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(44, 'Atendimento ao Cliente 24/7', 'Serviço de atendimento ao cliente disponível 24 horas por dia, 7 dias por semana, para todas as suas necessidades.', 3, 3, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:40', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(45, 'Consultoria em TI', 'Consultoria em tecnologia da informação para modernizar e proteger seus sistemas e dados.', 4, 4, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:40', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(46, 'Treinamento Profissional', 'Programas de treinamento e capacitação para aprimorar as habilidades da sua equipe.', 5, 5, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:40', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(47, 'Gestão de Projetos', 'Serviços de gestão de projetos para garantir entregas dentro do prazo e orçamento.', 6, 6, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:41', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(48, 'Serviços de Marketing Digital', 'Estratégias de marketing digital para aumentar a presença online da sua empresa e atrair mais clientes.', 7, 7, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:41', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(49, 'Consultoria Jurídica', 'Consultoria jurídica especializada em questões empresariais, contratuais e regulatórias.', 8, 8, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:41', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(50, 'Design Gráfico e Branding', 'Serviços de design gráfico para criação de identidade visual e branding para a sua marca.', 9, 9, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:41', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(51, 'Segurança Cibernética', 'Serviços de segurança cibernética para proteger sua empresa contra ameaças digitais e ataques.', 10, 10, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:41', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(52, 'Consultoria em Marketing', 'Consultoria especializada para otimizar campanhas de marketing e aumentar a visibilidade da sua empresa.', 1, 11, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:41', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(53, 'Desenvolvimento Web', 'Criação de sites personalizados para sua empresa com design responsivo e otimização SEO.', 2, 12, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:41', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(54, 'Suporte Técnico 24/7', 'Suporte técnico contínuo para manutenção e solução de problemas de infraestrutura de TI.', 3, 13, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:41', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(55, 'Assessoria de Imprensa', 'Serviço de assessoria de imprensa para melhorar a imagem da sua empresa e gerenciar crises de comunicação.', 4, 14, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:41', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(56, 'Treinamento Corporativo', 'Treinamento especializado em diversas áreas para o desenvolvimento contínuo da sua equipe.', 5, 15, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:41', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(57, 'Consultoria em Recursos Humanos', 'Consultoria para otimização de processos de recursos humanos, recrutamento e gestão de talentos.', 6, 16, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:41', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(58, 'Serviços de Tradução', 'Serviços de tradução profissional para vários idiomas, garantindo precisão e qualidade em cada projeto.', 7, 17, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:42', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(59, 'Gestão de Redes Sociais', 'Gestão estratégica de redes sociais para aumentar o engajamento e presença digital da sua empresa.', 8, 18, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:42', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(60, 'Consultoria em Finanças Empresariais', 'Consultoria financeira para gestão de fluxo de caixa, investimentos e planejamento financeiro.', 9, 19, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:42', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(61, 'Desenvolvimento de Aplicativos Móveis', 'Desenvolvimento de aplicativos móveis sob medida para facilitar a interação com seus clientes.', 10, 20, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:42', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(62, 'Serviço de Limpeza Empresarial', 'Limpeza profissional e regular para manter seu ambiente de trabalho sempre impecável.', 1, 21, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:42', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(63, 'Assessoria Financeira Pessoal', 'Assessoria para planejamento financeiro pessoal e gestão de investimentos.', 2, 22, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:42', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(64, 'Consultoria em Transformação Digital', 'Serviços de transformação digital para otimizar processos empresariais e integrar novas tecnologias.', 3, 23, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:42', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(65, 'Treinamento de Liderança', 'Treinamento focado no desenvolvimento de líderes eficazes e habilidades de gestão de equipes.', 4, 24, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:42', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(66, 'Consultoria em Comunicação Corporativa', 'Consultoria para aprimorar a comunicação interna e externa da sua empresa.', 5, 25, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:42', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(67, 'Marketing de Conteúdo', 'Estratégias de marketing de conteúdo para gerar engajamento e autoridade para sua marca.', 6, 26, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:42', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(68, 'Serviços de Auditoria', 'Auditoria interna e externa para garantir a conformidade e segurança financeira da sua empresa.', 7, 27, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:43', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(69, 'Gestão de Eventos Corporativos', 'Planejamento e execução de eventos corporativos, desde conferências até reuniões de equipe.', 8, 28, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:43', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(70, 'Consultoria em Sustentabilidade', 'Consultoria para empresas implementarem práticas sustentáveis em suas operações.', 9, 29, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:43', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(71, 'Desenvolvimento de E-commerce', 'Desenvolvimento de plataformas de e-commerce personalizadas para o seu negócio online.', 10, 30, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:43', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(72, 'Serviço de Fotografia Profissional', 'Serviços de fotografia para eventos corporativos, produtos e campanhas publicitárias.', 1, 31, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:43', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(73, 'Consultoria em Branding', 'Consultoria especializada para construção e gerenciamento da identidade da sua marca.', 2, 32, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:43', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(74, 'Gestão de Logística e Estoques', 'Serviços de gestão de logística e estoques para otimizar a distribuição de produtos.', 3, 33, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:43', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(75, 'Serviço de Tradução Juramentada', 'Tradução juramentada para documentos legais e oficiais com total precisão e autenticidade.', 4, 34, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:43', '2025-03-27 12:41:29');
INSERT INTO DB_INCEPTUS_PP.PRODUCT
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, CATEGORY_ID, COMPANY_ID, PRODUCT_STATUS, PRODUCT_RANK, PRODUCT_VIEW_QTY, IMG_URL, CREATED_AT, UPDATED_AT)
VALUES(76, 'Gestão de Atendimento ao Cliente', 'Serviços para melhorar e otimizar o atendimento ao cliente, com foco em excelência e satisfação.', 5, 35, 'A', 0.0, NULL, NULL, '2025-03-21 15:22:43', '2025-03-27 12:41:29');