select * from USER_TYPE;

INSERT INTO USER_TYPE (TYPE_ID, USER_TYPE) VALUES (1,'USER');
INSERT INTO USER_TYPE (TYPE_ID, USER_TYPE) VALUES (2,'COMPANY');
INSERT INTO USER_TYPE (TYPE_ID, USER_TYPE) VALUES (3,'ADMIN');
INSERT INTO USER_TYPE (TYPE_ID, USER_TYPE) VALUES (4,'SUSER');

-- UPDATE USER_TYPES ut SET USER_TYPE = 'SUSER' WHERE ut.USER_TYPE LIKE 'TESTE%';