CREATE PROCEDURE CREATE_RESET_CODE (IN V_USER_ID INT)
BEGIN
	INSERT INTO DB_INCEPTUS_PP.SEC_RST_CODE
	(USER_ID, GENERATED_CODE)
	VALUES(V_USER_ID,FLOOR(100000 + RAND() * 900000));
END

Create Procedure COMPANY_TOP() 
BEGIN
	select * from COMPANY c order by c.COMPANY_RANK desc limit 3;
END


CREATE PROCEDURE PRODUCT_TOP()
BEGIN
select p.PRODUCT_NAME, p.PRODUCT_DESCRIPTION, p.IMG_URL  from PRODUCT p ORDER BY p.PRODUCT_RANK DESC LIMIT 3;
END

CREATE PROCEDURE TRENDING_TOP()
BEGIN
	SELECT c.COMMENT_TEXT, com.COMPANY_NAME 
	FROM COMMENT c
	INNER JOIN COMPANY com ON c.COMPANY_ID = com.COMPANY_ID
	ORDER BY c.CREATED_AT DESC LIMIT 3;
END