CREATE TABLE DB_INCEPTUS_PP.USER_TYPE (
	TYPE_ID INT NOT NULL,
	USER_TYPE VARCHAR(100) NOT NULL,
	CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,	
	CONSTRAINT TYPE__PK PRIMARY KEY (TYPE_ID),
	CONSTRAINT TYPE_UNIQUE UNIQUE KEY (USER_TYPE)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci
COMMENT='Table containing user type data';

CREATE TABLE DB_INCEPTUS_PP.USER (
	USER_ID INT AUTO_INCREMENT NOT NULL,
	USER_NAME VARCHAR(100) NOT NULL,
	USER_EMAIL VARCHAR(100) NOT NULL,
	USER_PASSWORD VARCHAR(100) DEFAULT 'Mudar#1234' NOT NULL,
	USER_STATUS VARCHAR(1) DEFAULT 'A' NOT NULL COMMENT 'Values (A)ctive, (I)nactive',
	TYPE_ID INT NOT NULL,
	IMG_URL VARCHAR(100),
	CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,	
	CONSTRAINT USER_PK PRIMARY KEY (USER_ID),
	CONSTRAINT USER_UNIQUE UNIQUE KEY (USER_EMAIL),
	CONSTRAINT USER_TYPE_ID_FK FOREIGN KEY (TYPE_ID) REFERENCES DB_INCEPTUS_PP.USER_TYPE(TYPE_ID) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci
COMMENT='Table containing user data';


CREATE TABLE DB_INCEPTUS_PP.COMPANY (
	COMPANY_ID INT AUTO_INCREMENT NOT NULL,
	COMPANY_NAME VARCHAR(100) NOT NULL,
	COMPANY_DESCRIPTION VARCHAR(1000) NOT NULL,
	COMPANY_EMAIL VARCHAR(100) NOT NULL,
	COMPANY_PASSWORD VARCHAR(100) DEFAULT 'Mudar#1234' NOT NULL,
	COMPANY_SITE VARCHAR(100) NOT NULL,
	COMPANY_STATUS VARCHAR(1) DEFAULT 'A' NOT NULL,
	COMPANY_RANK INT,
	COMPANY_VIEW_QTY INT,
	TYPE_ID INT DEFAULT 2 NOT NULL,
	IMG_URL VARCHAR(100),
	CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,	
	CONSTRAINT COMPANY_PK PRIMARY KEY (COMPANY_ID),
	CONSTRAINT COMPANY_UNIQUE UNIQUE KEY (COMPANY_EMAIL)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci
COMMENT='Table containing company data';


CREATE TABLE DB_INCEPTUS_PP.CATEGORY (
	CATEGORY_ID INT AUTO_INCREMENT NOT NULL,
	CATEGORY_NAME VARCHAR(100) NOT NULL,
	CATEGORY_TYPE VARCHAR(100) NOT NULL,
	CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,	
	CONSTRAINT CATEGORY_PK PRIMARY KEY (CATEGORY_ID),
	CONSTRAINT CATEGORY_UNIQUE UNIQUE KEY (CATEGORY_NAME)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci
COMMENT='Table containing category data';


CREATE TABLE DB_INCEPTUS_PP.PRODUCT (
	PRODUCT_ID INT AUTO_INCREMENT NOT NULL,
	PRODUCT_NAME VARCHAR(100) NOT NULL,
	PRODUCT_DESCRIPTION VARCHAR(1000) NOT NULL,
	CATEGORY_ID INT NOT NULL,
	COMPANY_ID INT NOT NULL,
	PRODUCT_STATUS VARCHAR(1) DEFAULT 'A' NOT NULL,
	PRODUCT_RANK INT,
	PRODUCT_VIEW_QTY INT,
	IMG_URL VARCHAR(100),
	CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,	
	CONSTRAINT PRODUCT_PK PRIMARY KEY (PRODUCT_ID),
	CONSTRAINT PRODUCT_UNIQUE UNIQUE KEY (PRODUCT_NAME, COMPANY_ID),
	CONSTRAINT PRODUCT_CATEGORY_ID_FK FOREIGN KEY (CATEGORY_ID) REFERENCES DB_INCEPTUS_PP.CATEGORY(CATEGORY_ID) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT PRODUCT_COMPANY_ID_FK FOREIGN KEY (COMPANY_ID) REFERENCES DB_INCEPTUS_PP.COMPANY(COMPANY_ID) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci
COMMENT='Table containing prodcut data';


CREATE TABLE DB_INCEPTUS_PP.COMMENT (
	COMMENT_ID INT AUTO_INCREMENT NOT NULL,
	USER_ID INT NOT NULL,
	COMPANY_ID INT NOT NULL,
	PRODUCT_ID INT NOT NULL,
	COMMENT_TEXT VARCHAR(2000) NOT NULL,
	COMMENT_STATUS VARCHAR(1) DEFAULT 'A' NOT NULL,
	CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,		
	CONSTRAINT COMMENT_PK PRIMARY KEY (COMMENT_ID),
	CONSTRAINT COMMENT_USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES DB_INCEPTUS_PP.USER(USER_ID) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT COMMENT_COMPANY_ID_FK FOREIGN KEY (COMPANY_ID) REFERENCES DB_INCEPTUS_PP.COMPANY(COMPANY_ID) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT COMMENT_PRODUCT_ID_FK FOREIGN KEY (PRODUCT_ID) REFERENCES DB_INCEPTUS_PP.PRODUCT(PRODUCT_ID) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci
COMMENT='Table containing comment data';

