CREATE PROCEDURE UPD_COMPANY_RANK()
BEGIN
    DECLARE DONE BOOLEAN DEFAULT FALSE;
    DECLARE V_COMPANY BINARY(36);
    DECLARE LIST_COMPANY CURSOR FOR SELECT DISTINCT COMPANY_ID FROM COMPANY;
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE = TRUE;
    OPEN LIST_COMPANY;
	    READ_LOOP: LOOP
	        FETCH LIST_COMPANY INTO V_COMPANY;
	        IF DONE THEN
	            LEAVE READ_LOOP;
	        END IF;
	        UPDATE COMPANY 
			SET COMPANY_RANK = (SELECT IFNULL(AVG(COMMENT_RANK), 0.0) FROM COMMENT WHERE COMPANY_ID = V_COMPANY)
			WHERE COMPANY_ID = V_COMPANY;
	    END LOOP;  
    CLOSE LIST_COMPANY;
    COMMIT;
END;

CALL UPD_COMPANY_RANK;

CREATE PROCEDURE UPD_PRODUCT_RANK()
BEGIN
    DECLARE DONE BOOLEAN DEFAULT FALSE;
    DECLARE V_PRODUCT BINARY(36);
    DECLARE LIST_PRODUCT CURSOR FOR SELECT DISTINCT PRODUCT_ID FROM PRODUCT;
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE = TRUE;
    OPEN LIST_PRODUCT;
	    READ_LOOP: LOOP
	        FETCH LIST_PRODUCT INTO V_PRODUCT;
	        IF DONE THEN
	            LEAVE READ_LOOP;
	        END IF;
	        UPDATE PRODUCT 
			SET PRODUCT_RANK = (SELECT IFNULL(AVG(COMMENT_RANK), 0.0) FROM COMMENT WHERE PRODUCT_ID = V_PRODUCT)
			WHERE PRODUCT_ID = V_PRODUCT;
	    END LOOP;  
    CLOSE LIST_PRODUCT;
    COMMIT;
END;

CALL UPD_PRODUCT_RANK;