CREATE PROCEDURE UPD_COMPANY_RANK()
BEGIN
    DECLARE DONE BOOLEAN DEFAULT FALSE;
    DECLARE COMPANY INT;
    DECLARE LIST_COMPANY CURSOR FOR SELECT DISTINCT COMPANY_ID FROM COMPANY;
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE = TRUE;
    OPEN LIST_COMPANY;
	    READ_LOOP: LOOP
	        FETCH LIST_COMPANY INTO COMPANY;
	        IF DONE THEN
	            LEAVE READ_LOOP;
	        END IF;
	        UPDATE COMPANY 
			SET COMPANY_RANK = (SELECT IFNULL(AVG(COMMENT_RANK), 0.0) FROM COMMENT WHERE COMPANY_ID = COMPANY)
			WHERE COMPANY_ID = COMPANY;
	    END LOOP;  
    CLOSE LIST_COMPANY;
    COMMIT;
END;

CALL UPD_COMPANY_RANK;