SELECT * FROM USER;
SELECT * FROM COMPANY c ;
SELECT * FROM PRODUCT p ;
SELECT * FROM POST;
SELECT * FROM TAG;
SELECT * FROM SEC_RST_CODE;

update PRODUCT set PRODUCT_RANK = null;
update COMPANY set COMPANY_RANK = null;

INSERT INTO DB_INCEPTUS_PP.POST
(COMPANY_ID, POST_CONTENT, POST_STATUS)
VALUES(1, '', 'A');

INSERT INTO DB_INCEPTUS_PP.TAG
(TAG_TEXT, PRODUCT_ID, COMPANY_ID)
VALUES('PROD_TAG', 6, NULL);

INSERT INTO DB_INCEPTUS_PP.SEC_RST_CODE
(USER_ID, GENERATED_CODE)
VALUES(81,FLOOR(100000 + RAND() * 900000));

CREATE PROCEDURE CREATE_RESET_CODE (IN V_USER_ID INT)
BEGIN
	INSERT INTO DB_INCEPTUS_PP.SEC_RST_CODE
	(USER_ID, GENERATED_CODE)
	VALUES(V_USER_ID,FLOOR(100000 + RAND() * 900000));
END

CALL CREATE_RESET_CODE(84);

INSERT INTO DB_INCEPTUS_PP.POST
(POST_CONTENT)